name: default
channels:
- conda-forge
- nodefaults
dependencies:
- python >=3.9
- numpy *
- numba *
- jax *
- jaxlib *
- poetry *
- bump-my-version *
- coverage *
- pytest *
- pytest-benchmark *
- furo *
- linkify-it-py *
- myst-parser *
- sphinx *
- sphinx-autobuild *
- sphinxcontrib-apidoc *
- pip
- pip:
  - sphinx-last-updated-by-git
  - -e .
