version: "3"

tasks:
  export:
    desc: "Export a conda environment file."
    cmds:
      - pixi project export conda-environment environment.yml
  diff:
    desc: "Show differences between modules."
    cmds:
      - pixi run python -m autojax.util.mod_diff
  clean:
    desc: "Clean benchmark files."
    cmds:
      - rm -rf .benchmarks
      - find batch \( -name '*.out' -o -name '*.err' -o -name '*.sh' \) -delete
